#!/usr/bin/env python3
#coding: utf-8
#@author: linsheng
import urllib
import urllib2
import re

#爬取视频
x=0
def getfile(wenjian):
    
    f=open(wenjian)
    line=f.readlines()
    for lins in line:
        getview(lins)
    f.close()    
def getview(lins):
    global x
    request=urllib2.Request(lins)
    page=urllib2.urlopen(lins)
    html=page.read()
    
    reg=r'<meta.*content="(.*?)".*?/>'
    imge=re.compile(reg)
    imglist=re.findall(imge,html)
    
    for imgurl in imglist:
        if imgurl.startswith("http") and imgurl.endswith(".mp4"):
            resp=urllib2.urlopen(imgurl)
            respHtml=resp.read()
            picFile=open('%s.mp4' % x,"wb")
            picFile.write(respHtml)
            picFile.close()
            x =x+1
    print 'done'         


# main  
if __name__ == "__main__":             
     url="http://va1.vjshi.com/flv/2016-01-29/2015-2ac72f3f346a741e3992723a7d3bfb5d.mp4"
    #wenjian="C:/Users/pc/Desktop/videlurl.txt"
    #getfile(wenjian)
     getview(url)
